// Generated by CoffeeScript 1.10.0
(function() {
  var Mongoose, app, db, express;

  process.env.NODE_ENV = process.env.NODE_ENV || 'development';

  Mongoose = require('./config/mongoose');

  express = require('./config/express');

  db = Mongoose();

  app = express();

  app.listen(3000);

  module.exports = app;

  console.log('Server running at http://localhost:3000/');

}).call(this);

//# sourceMappingURL=server.js.map
