// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    sessionSecret: 'developmentSessionSecret',
    db: 'mongodb://localhost/my-blog'
  };

}).call(this);

//# sourceMappingURL=development.js.map
