// Generated by CoffeeScript 1.10.0
(function() {
  var config, mongoose;

  config = require('./config');

  mongoose = require('mongoose');

  module.exports = function() {
    var db;
    db = mongoose.connect(config.db);
    require('../app/models/article');
    return db;
  };

}).call(this);

//# sourceMappingURL=mongoose.js.map
