// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(app) {
    var index;
    index = require('../controllers/index.server.controller');
    app.get('/', index.render);
  };

}).call(this);

//# sourceMappingURL=index.route.js.map
