// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(app) {
    var sync;
    sync = require('../controllers/sync.server.controller');
    app.route('/sync').get(sync.listNotebooks);
    return app.route('/sync/test').get(sync.getNoteContent);
  };

}).call(this);

//# sourceMappingURL=sync.route.js.map
